// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file video.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "video.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Video::Video()
{
}

Video::~Video()
{
}

Video::Video(const Video &x)
{
    m_message = x.m_message;
}

Video::Video(Video &&x)
{
    m_message = std::move(x.m_message);
}

Video& Video::operator=(const Video &x)
{
    m_message = x.m_message;
    
    return *this;
}

Video& Video::operator=(Video &&x)
{
    m_message = std::move(x.m_message);
    
    return *this;
}

size_t Video::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += ((1000000) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    return current_alignment - initial_alignment;
}

size_t Video::getCdrSerializedSize(const Video& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += ((1000000) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    return current_alignment - initial_alignment;
}

void Video::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_message;
}

void Video::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_message;
}

size_t Video::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            

    return current_align;
}

bool Video::isKeyDefined()
{
    return false;
}

void Video::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
}